2022-10-13 11:47:53,827 ERROR: Exception on /index/ [GET] [in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/Users/sam/PycharmProjects/flask_lessons/app/routes.py", line 29, in before_request
    g.locale = str(get_locale())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_babel/__init__.py", line 222, in get_locale
    babel = current_app.extensions['babel']
KeyError: 'babel'
2022-10-13 11:49:42,972 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 11:49:54,372 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 12:08:13,754 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 12:09:37,166 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 12:13:21,199 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 12:13:36,344 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 12:15:59,093 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:50]
2022-10-13 13:28:16,320 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:29:46,525 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:31:10,547 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:33:37,940 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:36:08,545 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:36:10,931 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:37:53,917 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:39:44,666 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:40:46,991 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:43:38,791 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:45:06,944 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:46:28,989 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:47:38,813 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:48:31,968 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-13 13:52:55,643 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:51]
2022-10-15 13:37:13,077 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:69]
2022-10-15 13:38:08,668 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:69]
2022-10-15 13:38:23,567 ERROR: Exception on /user/sam [GET] [in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sam/PycharmProjects/flask_lessons/app/main/routes.py", line 88, in user
    next_url = url_for('main.user', username=user.username, page=posts.next_num) if posts.has_next else None
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['page', 'username']. Did you mean 'main.user' instead?
