2022-10-08 17:29:34,633 ERROR: Exception on /explore [GET] [in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sam/PycharmProjects/flask_lessons/app/routes.py", line 69, in explore
    return render_template('index.html', title='Explore', posts=posts, pagination=pagination)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/index.html", line 5, in block "content"
    共有 {{ posts |length }} 条内容：
TypeError: object of type 'BaseQuery' has no len()
2022-10-08 17:32:29,790 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:32:38,315 ERROR: Exception on /explore [GET] [in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sam/PycharmProjects/flask_lessons/app/routes.py", line 61, in explore
    posts = posts_obj.slice(start, end)
AttributeError: 'list' object has no attribute 'slice'
2022-10-08 17:33:47,622 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:33:55,885 ERROR: Exception on /explore [GET] [in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sam/PycharmProjects/flask_lessons/app/routes.py", line 70, in explore
    return render_template('index.html', title='Explore', posts=posts, pagination=pagination)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/sam/PycharmProjects/flask_lessons/app/templates/index.html", line 5, in block "content"
    共有 {{ posts |length }} 条内容：
TypeError: object of type 'BaseQuery' has no len()
2022-10-08 17:41:18,120 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:41:33,170 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:41:33,758 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:42:00,077 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:42:00,656 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:42:19,316 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:42:19,871 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:44:50,527 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:45:23,855 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:45:24,453 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:46:52,285 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:47:10,338 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:51:29,288 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 17:56:39,861 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 18:00:27,620 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 18:00:43,599 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
2022-10-08 18:20:17,517 INFO: Microblog startup [in /Users/sam/PycharmProjects/flask_lessons/app/__init__.py:40]
